Feature/custom nfts
Psychedelic/plug pull request #588
Opened 2022-09-05 21:20 UTC by Cancuuu

## ADD CUSTOM NFTS FEATURE
ISSUE NUMBER #559 

- Added buttons on home page
- Added GET_NFT_INFO method and created in plug-controller too
- Added ADD_CUSTOM_NFT method and created in plug-controller too
- New add custom nft components and pages created

### Type of changes included:

- [x] Components
- [ ] Business Logic
- [ ] Bug fixes
- [x] Styling
- [x] Code Refactor

### Clubhouse Tickets Related:

### Screenshots/Gifs:

![image](https://user-images.githubusercontent.com/52618089/188512848-b817afdd-95cd-4a32-9dc5-9b7fec451922.png)
![image](https://user-images.githubusercontent.com/52618089/188512873-22904280-b6e5-4b91-ac17-7b3abc6abafb.png)
![image](https://user-images.githubusercontent.com/52618089/188512894-c47fa36a-9cdd-4fbf-99f4-e558afc09a3f.png)

### Notes:

*Place special notes here*

### Tested on:

- [x] Chrome
- [ ] Firefox
- [ ] Safari

2022-09-06 10:14 UTC, riveign commented
@Cancuuu question, what should we do with the thumbnail image?

2022-09-07 14:10 UTC, angarita-dev requested changes

2022-09-07 14:10 UTC, angarita-dev commented on package.json
> +    "@psychedelic/plug-controller": "0.19.8",
We should use version `0.20`

2022-09-07 14:10 UTC, angarita-dev commented on source/Background/Keyring/index.js
> +    console.log('se activa get assets!');
Remove debugging `console.log`

2022-09-07 14:10 UTC, angarita-dev commented on source/Background/Keyring/index.js
> +      console.log('el keyring getState me devuelve', wallets, currentWalletId);
same ^

2022-09-07 14:10 UTC, angarita-dev commented on source/Background/Keyring/index.js
> +        console.log('desde plug luego de llamar a registerNFT del keyring ->', nfts);
^

2022-09-07 14:10 UTC, angarita-dev commented on source/components/Tokens/components/TokenSelector/index.jsx
> +        />  <Typography variant="h5" data-testid="wallet-name">Add Token</Typography>
Maybe we could add this text to `i18n`

2022-09-07 14:10 UTC, angarita-dev commented on source/components/Tokens/index.jsx
> +  const [activateButton, setActivateButton] = useState(false);
We should probably change this to `displayCustomToken` or something more descriptive

2022-09-07 14:10 UTC, angarita-dev commented on source/views/Extension/Views/AddNFT/Steps/Step2.jsx
> +  // const displayToken = parseTokenBySymbol(selectedToken); // podemos agregar un parser para terminar con el ultimo objeto
remove comment

2022-09-07 14:10 UTC, angarita-dev commented on source/views/Extension/Views/AddNFT/Steps/Step2.jsx
> +    console.log('el selected token es ->', selectedToken);
console.log

2022-09-07 14:10 UTC, angarita-dev commented on source/views/Extension/Views/AddNFT/components/CustomNFT.jsx
> +  const isInvalidCanisterError = tokenError === 'The provided canister id is invalid';
maybe we could move this to an object? or a helper function

2022-09-07 14:10 UTC, angarita-dev commented on source/views/Extension/Views/AddNFT/components/CustomNFT.jsx
> +                        ? t('addNFT.invalidCanisterTokenError')
yeah maybe using an object we could get the translation string directly

2022-09-15 16:00 UTC, angarita-dev approved these changes

2022-09-15 16:00 UTC, angarita-dev commented on source/views/Extension/Views/AddNFT/hooks/useSteps.jsx
> +  const rightButton = <LinkButton value={t('common.close')} onClick={() => handleClose()} />;
```suggestion
  const rightButton = <LinkButton value={t('common.close')} onClick={handleClose} />;
```

2022-09-15 16:00 UTC, angarita-dev commented on source/views/Extension/Views/AddNFT/Steps/Step2.jsx
> +    console.log('salio todo correcto')
```suggestion
```
🙅

2022-09-15 17:55 UTC, merged