Feat/import identity string
Psychedelic/plug pull request #648
Opened 2022-10-20 19:27 UTC by Cancuuu

## Import Private key

### Type of changes included:

- [x] Components
- [ ] Business Logic
- [ ] Bug fixes
- [x] Styling
- [ ] Code Refactor

### Ticket related:  #620  
### Screenshots/Gifs:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/52618089/197039379-eee99382-cd0d-47f2-b392-09c5ef7f3f82.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/52618089/197039425-856ef7ff-a5eb-4bf3-930c-ece6431f4f89.png">

### Tested on:

- [x] Chrome
- [ ] Firefox
- [ ] Safari

2022-10-26 13:29 UTC, angarita-dev requested changes

2022-10-26 13:29 UTC, angarita-dev commented on source/views/Extension/Views/ImportPrivateKey/Steps/Step2.jsx
> +  const [disabled, setDisabled] = useState(false);
We should invert the `disabled` value logic, if `true` the button should be disabled

2022-11-02 15:57 UTC, Cancuuu commented
@angarita-dev

2022-11-04 01:20 UTC, angarita-dev approved these changes

2022-11-04 02:39 UTC, merged